services:
  db-mysql:
    image: mysql:8.0.33
    hostname: db-mysql
    container_name: db-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: lucasdb
      MYSQL_USER: parisi
      MYSQL_PASSWORD: lucas123
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot" ]
      interval: 5s
      retries: 10
      start_period: 10s
    networks:
      - app-network

networks:
  app-network:
